/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omms;

import java.awt.Color;
import omms.accountantDashboardInternalJframe.AccBillDash;
import omms.accountantDashboardInternalJframe.AccPaymentDash;
import omms.accountantDashboardInternalJframe.AccViewDash;
import omms.hallAuthoDashboardInternalJframe.HallAuthoBillDash;
import omms.hallAuthoDashboardInternalJframe.HallAuthoFoodDash;
import omms.hallAuthoDashboardInternalJframe.HallAuthoViewDash;

/**
 *
 * @author Asus
 */
public class DashboardHallAutho extends javax.swing.JFrame {

    int sid = 0, fmd = 0, bmd = 0;

    /**
     * Creates new form NewDashboard
     */
    public DashboardHallAutho() {
        initComponents();
        setTitle("Hall Authority Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        billMngPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        billMngLbl = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        stdInfPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        stdInfLbl = new javax.swing.JLabel();
        foodMngPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        foodMngLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JLabel();
        dashhboardPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(33, 102, 142));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        billMngPanel.setBackground(new java.awt.Color(33, 102, 142));
        billMngPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billMngPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billMngPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                billMngPanelMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(33, 102, 142));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/receipt_dollar_36px.png"))); // NOI18N

        billMngLbl.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        billMngLbl.setForeground(new java.awt.Color(255, 255, 255));
        billMngLbl.setText("Bill Management");

        javax.swing.GroupLayout billMngPanelLayout = new javax.swing.GroupLayout(billMngPanel);
        billMngPanel.setLayout(billMngPanelLayout);
        billMngPanelLayout.setHorizontalGroup(
            billMngPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billMngPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(billMngLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        billMngPanelLayout.setVerticalGroup(
            billMngPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(billMngLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(billMngPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 310, 60));

        logoPanel.setBackground(new java.awt.Color(253, 253, 253));

        jLabel15.setBackground(new java.awt.Color(253, 253, 253));
        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\CSE-MIST\\MIST Project\\CSE Alumni Website\\assets\\img\\mist_pattern_logo.png")); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );

        sidePanel.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 160));

        stdInfPanel.setBackground(new java.awt.Color(33, 102, 142));
        stdInfPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stdInfPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stdInfPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stdInfPanelMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(33, 102, 142));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/view_32px.png"))); // NOI18N

        stdInfLbl.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        stdInfLbl.setForeground(new java.awt.Color(255, 255, 255));
        stdInfLbl.setText("Student Info ");

        javax.swing.GroupLayout stdInfPanelLayout = new javax.swing.GroupLayout(stdInfPanel);
        stdInfPanel.setLayout(stdInfPanelLayout);
        stdInfPanelLayout.setHorizontalGroup(
            stdInfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stdInfPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(stdInfLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        stdInfPanelLayout.setVerticalGroup(
            stdInfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(stdInfLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(stdInfPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 310, 60));

        foodMngPanel.setBackground(new java.awt.Color(33, 102, 142));
        foodMngPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                foodMngPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                foodMngPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                foodMngPanelMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(33, 102, 142));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/money_bag_28px.png"))); // NOI18N

        foodMngLbl.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        foodMngLbl.setForeground(new java.awt.Color(255, 255, 255));
        foodMngLbl.setText("Food Management");

        javax.swing.GroupLayout foodMngPanelLayout = new javax.swing.GroupLayout(foodMngPanel);
        foodMngPanel.setLayout(foodMngPanelLayout);
        foodMngPanelLayout.setHorizontalGroup(
            foodMngPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodMngPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(foodMngLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        foodMngPanelLayout.setVerticalGroup(
            foodMngPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(foodMngLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(foodMngPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 310, 60));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 780));

        jPanel2.setBackground(new java.awt.Color(70, 139, 178));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 40)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("WELCOME TO THE DASHBOARD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 860, 170));

        jPanel9.setBackground(new java.awt.Color(253, 253, 253));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("OSMANY HALL MESS MANAGEMENT SYSTEM");

        exitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/criss-cross (1).png"))); // NOI18N
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 860, 80));

        dashhboardPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dashhboardPanelLayout = new javax.swing.GroupLayout(dashhboardPanel);
        dashhboardPanel.setLayout(dashhboardPanelLayout);
        dashhboardPanelLayout.setHorizontalGroup(
            dashhboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        dashhboardPanelLayout.setVerticalGroup(
            dashhboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(dashhboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 860, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void billMngPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billMngPanelMousePressed
        // TODO add your handling code here:
        billMngPanel.setBackground(new Color(129, 214, 163));
        foodMngPanel.setBackground(new Color(33, 102, 142));
        stdInfPanel.setBackground(new Color(33, 102, 142));
        fmd = 1;
        sid = bmd = 0;
        billMngLbl.setForeground(Color.BLACK); 
        stdInfLbl.setForeground(Color.WHITE);
        foodMngLbl.setForeground(Color.WHITE);     
        
        dashhboardPanel.removeAll();
        HallAuthoBillDash sid = new HallAuthoBillDash();
        dashhboardPanel.add(sid).setVisible(true);
    }//GEN-LAST:event_billMngPanelMousePressed

    private void billMngPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billMngPanelMouseEntered
        // TODO add your handling code here:
        if (fmd != 1) {
            billMngPanel.setBackground(new Color(45, 45, 45));
        }
    }//GEN-LAST:event_billMngPanelMouseEntered

    private void billMngPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billMngPanelMouseExited
        // TODO add your handling code here:
        if (fmd != 1) {
            billMngPanel.setBackground(new Color(33, 102, 142));
        }
    }//GEN-LAST:event_billMngPanelMouseExited

    private void foodMngPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMngPanelMouseEntered
        // TODO add your handling code here:
        if (bmd != 1) {
            foodMngPanel.setBackground(new Color(45, 45, 45));
        }        
    }//GEN-LAST:event_foodMngPanelMouseEntered

    private void foodMngPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMngPanelMouseExited
        // TODO add your handling code here:
        if (bmd != 1) {
            foodMngPanel.setBackground(new Color(33, 102, 142));
        }
    }//GEN-LAST:event_foodMngPanelMouseExited

    private void foodMngPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodMngPanelMousePressed
        // TODO add your handling code here:
        foodMngPanel.setBackground(new Color(129, 214, 163));
        stdInfPanel.setBackground(new Color(33, 102, 142));
        billMngPanel.setBackground(new Color(33, 102, 142));
        bmd = 1;
        fmd = sid = 0;
        foodMngLbl.setForeground(Color.BLACK);   
        billMngLbl.setForeground(Color.WHITE); 
        stdInfLbl.setForeground(Color.WHITE);  
        
        dashhboardPanel.removeAll();
        HallAuthoFoodDash sid = new HallAuthoFoodDash();
        dashhboardPanel.add(sid).setVisible(true);
    }//GEN-LAST:event_foodMngPanelMousePressed

    private void stdInfPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdInfPanelMousePressed
        // TODO add your handling code here:
        stdInfPanel.setBackground(new Color(129, 214, 163));
        foodMngPanel.setBackground(new Color(33, 102, 142));
        billMngPanel.setBackground(new Color(33, 102, 142));
        sid = 1;
        fmd = bmd = 0;
        stdInfLbl.setForeground(Color.BLACK);   
        billMngLbl.setForeground(Color.WHITE); 
        foodMngLbl.setForeground(Color.WHITE);      
        
        dashhboardPanel.removeAll();
        HallAuthoViewDash sid = new HallAuthoViewDash();
        dashhboardPanel.add(sid).setVisible(true);
    }//GEN-LAST:event_stdInfPanelMousePressed

    private void stdInfPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdInfPanelMouseExited
        // TODO add your handling code here:
        if (sid != 1) {
            stdInfPanel.setBackground(new Color(33, 102, 142));
        }
    }//GEN-LAST:event_stdInfPanelMouseExited

    private void stdInfPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdInfPanelMouseEntered
        // TODO add your handling code here:
        if (sid != 1) {
            stdInfPanel.setBackground(new Color(45, 45, 45));
        }
    }//GEN-LAST:event_stdInfPanelMouseEntered


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billMngLbl;
    private javax.swing.JPanel billMngPanel;
    private javax.swing.JDesktopPane dashhboardPanel;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel foodMngLbl;
    private javax.swing.JPanel foodMngPanel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel stdInfLbl;
    private javax.swing.JPanel stdInfPanel;
    // End of variables declaration//GEN-END:variables

}
