/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omms;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Login extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        initialize();
    }

    public void initialize() {
        conn = Jconnection.ConnecrDb(); // set connection with database        
        usernameTxt.requestFocus(); // setitng the focus to the Hall Id searchDate button
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        aboutUsLbl.setFont(new java.awt.Font("Bell MT", 0, 18));
        aboutUsLbl.setForeground(new Color(255, 255, 255));
        setTitle("Login");
    }

    
    
    
    
    public void checkLoginValidity() {
        try {
            ps = conn.prepareStatement("SELECT * FROM login");
            rs = ps.executeQuery();
            int chk = 0;
            while (rs.next()) {
                if (usernameTxt.getText().toString().trim().equals(rs.getString(1)) && passwordTxt.getText().toString().trim().equals(rs.getString(2))) {
                    try {
                        switch (rs.getString(1)) {
                            case "accountant":
                                {
                                    UserLog.name = "accountant";
                                    DashboardAccountant das = new DashboardAccountant();
                                    das.setVisible(true);
                                    this.setVisible(false);
                                    break;
                                }
                            case "mess":
                                {
                                    UserLog.name = "mess";
                                    DashboardMess das = new DashboardMess();
                                    das.setVisible(true);
                                    this.setVisible(false);
                                    break;
                                }
                            case "provost":
                                {
                                    UserLog.name = "provost";
                                    DashboardHallAutho das = new DashboardHallAutho();
                                    das.setVisible(true);
                                    this.setVisible(false);
                                    break;
                                }
                            default:
                                break;
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Oops! There are some problems!", "Unknown Error Occured!", JOptionPane.ERROR_MESSAGE);
                        ps.close();
                        rs.close();
                        return;
                    }
                    chk++;
                }
            }
            if (chk == 0) {
                usernameTxt.requestFocusInWindow();
                JOptionPane.showMessageDialog(null, "Username or Password is wrong!", "Login Error", JOptionPane.ERROR_MESSAGE);
                ps.close();
                rs.close();
                return;
            }
            ps.close();
            rs.close();
        } catch (Exception e) {
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passwordTxt = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        aboutUsLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        crossLbl = new javax.swing.JLabel();
        loginLbl = new javax.swing.JLabel();
        rightLbl = new javax.swing.JLabel();
        leftLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.setBackground(new Color(0,0,0,0));

        usernameLbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        usernameLbl.setForeground(new java.awt.Color(255, 255, 255));
        usernameLbl.setText("Username");
        jPanel1.add(usernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 130, 50));

        usernameTxt.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(102, 102, 102));
        usernameTxt.setText("Enter Username");
        usernameTxt.setBorder(null);
        usernameTxt.setCaretColor(new java.awt.Color(204, 204, 204));
        usernameTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameTxt.setOpaque(false);
        usernameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTxtFocusGained(evt);
            }
        });
        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 440, 40));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 440, 20));

        passwordTxt.setFont(new java.awt.Font("Calibri", 0, 22)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(153, 153, 153));
        passwordTxt.setText("jPasswordField1");
        passwordTxt.setBorder(null);
        passwordTxt.setCaretColor(new java.awt.Color(204, 204, 204));
        passwordTxt.setOpaque(false);
        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTxtFocusGained(evt);
            }
        });
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        jPanel1.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 440, 40));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 440, 20));

        aboutUsLbl.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        aboutUsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutUsLbl.setText("About Us");
        aboutUsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutUsLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutUsLblMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutUsLblMousePressed(evt);
            }
        });
        jPanel1.add(aboutUsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 680, 90, 30));

        passwordLbl.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordLbl.setText("Password");
        jPanel1.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 130, 50));

        crossLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crossLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/criss-cross (1).png"))); // NOI18N
        crossLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossLblMouseClicked(evt);
            }
        });
        jPanel1.add(crossLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 40, 60, 50));

        loginLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginLbl.setForeground(new java.awt.Color(255, 255, 255));
        loginLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/login.png"))); // NOI18N
        loginLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLblMouseClicked(evt);
            }
        });
        jPanel1.add(loginLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 180, 80));

        rightLbl.setForeground(new java.awt.Color(255, 255, 255));
        rightLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/right.png"))); // NOI18N
        rightLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(rightLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 670, 760));

        leftLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/leftLbl.png"))); // NOI18N
        jPanel1.add(leftLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 760));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1160, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
        checkLoginValidity();
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void usernameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtFocusGained
        // TODO add your handling code here:
        if (usernameTxt.getText().equals("Enter Username")) {
            usernameTxt.setText("");
        }
        usernameTxt.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_usernameTxtFocusGained

    private void passwordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusGained
        // TODO add your handling code here:
        passwordTxt.setText("");
        usernameTxt.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_passwordTxtFocusGained

    private void loginLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLblMouseClicked
        // TODO add your handling code here:
        checkLoginValidity();
    }//GEN-LAST:event_loginLblMouseClicked

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
        passwordTxt.requestFocusInWindow();
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void crossLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossLblMouseClicked
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_crossLblMouseClicked

    private void aboutUsLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsLblMouseEntered
        // TODO add your handling code here:
        aboutUsLbl.setFont(new java.awt.Font("Bell MT", 0, 22));
        aboutUsLbl.setForeground(new Color(0, 204, 255));
    }//GEN-LAST:event_aboutUsLblMouseEntered

    private void aboutUsLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsLblMouseExited
        // TODO add your handling code here:
        aboutUsLbl.setFont(new java.awt.Font("Bell MT", 0, 18));
        aboutUsLbl.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_aboutUsLblMouseExited

    private void aboutUsLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsLblMousePressed
        // TODO add your handling code here:
        AboutUs st = new AboutUs();
        st.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_aboutUsLblMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutUsLbl;
    private javax.swing.JLabel crossLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel leftLbl;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel rightLbl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
