/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omms.dashboardInternalJframe;

import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import omms.GroupCreate;
import omms.GroupDelete;
import omms.GroupItemAssign;
import omms.GroupStdAssign;

/**
 *
 * @author Asus
 */
public class GroupingDash extends javax.swing.JInternalFrame {

    /**
     * Creates new form DailyMealSheetDash
     */
    public GroupingDash() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createGrpBtn = new javax.swing.JButton();
        stdGrpAsgBtn = new javax.swing.JButton();
        grpFoodBtn = new javax.swing.JButton();
        grpdelBtn = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        createGrpBtn.setBackground(new java.awt.Color(255, 255, 255));
        createGrpBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        createGrpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/people_64px.png"))); // NOI18N
        createGrpBtn.setText("<html> <body> <p style=\"text-align:center\">Create Group</p> </body> </html>");
        createGrpBtn.setBorder(null);
        createGrpBtn.setFocusPainted(false);
        createGrpBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createGrpBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createGrpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGrpBtnActionPerformed(evt);
            }
        });

        stdGrpAsgBtn.setBackground(new java.awt.Color(255, 255, 255));
        stdGrpAsgBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        stdGrpAsgBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/groupStd.png"))); // NOI18N
        stdGrpAsgBtn.setText("<html> <body> <p style=\"text-align:center\">Student Group Assign</p> </body> </html>");
        stdGrpAsgBtn.setBorder(null);
        stdGrpAsgBtn.setFocusPainted(false);
        stdGrpAsgBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stdGrpAsgBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stdGrpAsgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdGrpAsgBtnActionPerformed(evt);
            }
        });

        grpFoodBtn.setBackground(new java.awt.Color(255, 255, 255));
        grpFoodBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        grpFoodBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/groupItem.png"))); // NOI18N
        grpFoodBtn.setText("<html> <body> <p style=\"text-align:center\">Group Food Items</p> </body> </html>");
        grpFoodBtn.setBorder(null);
        grpFoodBtn.setFocusPainted(false);
        grpFoodBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        grpFoodBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        grpFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grpFoodBtnActionPerformed(evt);
            }
        });

        grpdelBtn.setBackground(new java.awt.Color(255, 255, 255));
        grpdelBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        grpdelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/delete_64px.png"))); // NOI18N
        grpdelBtn.setText("<html> <body> <p style=\"text-align:center\">Delete Group</p> </body> </html>");
        grpdelBtn.setBorder(null);
        grpdelBtn.setFocusPainted(false);
        grpdelBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        grpdelBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        grpdelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grpdelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stdGrpAsgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(grpdelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(createGrpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grpFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grpFoodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createGrpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdGrpAsgBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grpdelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grpFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grpFoodBtnActionPerformed
        // TODO add your handling code here:
        GroupItemAssign st = new GroupItemAssign();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_grpFoodBtnActionPerformed

    private void stdGrpAsgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdGrpAsgBtnActionPerformed
        // TODO add your handling code here:
        GroupStdAssign st = new GroupStdAssign();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_stdGrpAsgBtnActionPerformed

    private void createGrpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGrpBtnActionPerformed
        // TODO add your handling code here:
        GroupCreate st = new GroupCreate();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_createGrpBtnActionPerformed

    private void grpdelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grpdelBtnActionPerformed
        // TODO add your handling code here:
        GroupDelete st = new GroupDelete();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();        
    }//GEN-LAST:event_grpdelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createGrpBtn;
    private javax.swing.JButton grpFoodBtn;
    private javax.swing.JButton grpdelBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stdGrpAsgBtn;
    // End of variables declaration//GEN-END:variables
}
