/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omms.dashboardInternalJframe;

import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import omms.StdHallAdmission;
import omms.StdInfoUpdate;

/**
 *
 * @author Asus
 */
public class HallAdmissionDash extends javax.swing.JInternalFrame {

    /**
     * Creates new form HallAdmissionDash
     */
    public HallAdmissionDash() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stdAddBtn = new javax.swing.JButton();
        stdView = new javax.swing.JButton();
        stdUpdtBtn = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        stdAddBtn.setBackground(new java.awt.Color(255, 255, 255));
        stdAddBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        stdAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/admission_64px.png"))); // NOI18N
        stdAddBtn.setText("<html> <body> <p style=\"text-align:center\">Student Admission</p> </body> </html>");
        stdAddBtn.setBorder(null);
        stdAddBtn.setFocusPainted(false);
        stdAddBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stdAddBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stdAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdAddBtnActionPerformed(evt);
            }
        });

        stdView.setBackground(new java.awt.Color(255, 255, 255));
        stdView.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        stdView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/view_64px.png"))); // NOI18N
        stdView.setText("<html> <body> <p style=\"text-align:center\">Student Info View</p> </body> </html>");
        stdView.setBorder(null);
        stdView.setFocusPainted(false);
        stdView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stdView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stdView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdViewActionPerformed(evt);
            }
        });

        stdUpdtBtn.setBackground(new java.awt.Color(255, 255, 255));
        stdUpdtBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        stdUpdtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/Stdupdate_64px.png"))); // NOI18N
        stdUpdtBtn.setText("<html> <body> <p style=\"text-align:center\">Student Info Update</p> </body> </html>");
        stdUpdtBtn.setBorder(null);
        stdUpdtBtn.setFocusPainted(false);
        stdUpdtBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stdUpdtBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stdUpdtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdUpdtBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(stdAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(stdUpdtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stdView, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdUpdtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(stdView, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stdUpdtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdUpdtBtnActionPerformed
        // TODO add your handling code here:
        StdInfoUpdate st = new StdInfoUpdate();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_stdUpdtBtnActionPerformed

    private void stdAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdAddBtnActionPerformed
        // TODO add your handling code here:
        StdHallAdmission st = new StdHallAdmission();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_stdAddBtnActionPerformed

    private void stdViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdViewActionPerformed
        // TODO add your handling code here:
        //Std st = new ();
        //st.setVisible(true);
        //SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_stdViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stdAddBtn;
    private javax.swing.JButton stdUpdtBtn;
    private javax.swing.JButton stdView;
    // End of variables declaration//GEN-END:variables
}
