/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omms.dashboardInternalJframe;

import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import omms.TempFoodView;
import omms.TemporaryFoodIn;
import omms.TmpFoodUpdate;

/**
 *
 * @author Asus
 */
public class TempFoodDash extends javax.swing.JInternalFrame {

    /**
     * Creates new form TempFoodDash
     */
    public TempFoodDash() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tempFoodInBtn = new javax.swing.JButton();
        tempFoodViewBtn = new javax.swing.JButton();
        tempFoodUpdateBtn = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        tempFoodInBtn.setBackground(new java.awt.Color(255, 255, 255));
        tempFoodInBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        tempFoodInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/put-in-cart.png"))); // NOI18N
        tempFoodInBtn.setText("<html> <body> <p style=\"text-align:center\">Temp Food In</p> </body> </html>");
        tempFoodInBtn.setBorder(null);
        tempFoodInBtn.setFocusPainted(false);
        tempFoodInBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tempFoodInBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tempFoodInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempFoodInBtnActionPerformed(evt);
            }
        });

        tempFoodViewBtn.setBackground(new java.awt.Color(255, 255, 255));
        tempFoodViewBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        tempFoodViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/mug.png"))); // NOI18N
        tempFoodViewBtn.setText("<html> <body> <p style=\"text-align:center\">Temp Food View</p> </body> </html>");
        tempFoodViewBtn.setBorder(null);
        tempFoodViewBtn.setFocusPainted(false);
        tempFoodViewBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tempFoodViewBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tempFoodViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempFoodViewBtnActionPerformed(evt);
            }
        });

        tempFoodUpdateBtn.setBackground(new java.awt.Color(255, 255, 255));
        tempFoodUpdateBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        tempFoodUpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/update_64px.png"))); // NOI18N
        tempFoodUpdateBtn.setText("<html> <body> <p style=\"text-align:center\">Temp Food Update</p> </body> </html>");
        tempFoodUpdateBtn.setBorder(null);
        tempFoodUpdateBtn.setFocusPainted(false);
        tempFoodUpdateBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tempFoodUpdateBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tempFoodUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempFoodUpdateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(tempFoodInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(tempFoodViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tempFoodUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempFoodInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempFoodViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(tempFoodUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempFoodInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempFoodInBtnActionPerformed
        // TODO add your handling code here:
        TemporaryFoodIn st = new TemporaryFoodIn();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_tempFoodInBtnActionPerformed

    private void tempFoodViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempFoodViewBtnActionPerformed
        // TODO add your handling code here:
        TempFoodView st = new TempFoodView();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_tempFoodViewBtnActionPerformed

    private void tempFoodUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempFoodUpdateBtnActionPerformed
        // TODO add your handling code here:
        TmpFoodUpdate st = new TmpFoodUpdate();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_tempFoodUpdateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tempFoodInBtn;
    private javax.swing.JButton tempFoodUpdateBtn;
    private javax.swing.JButton tempFoodViewBtn;
    // End of variables declaration//GEN-END:variables
}
