/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omms.accountantDashboardInternalJframe;

import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import omms.AccountPayment;
import omms.AccountPaymentDelete;
import omms.AccountPaymentHistoryView;

/**
 *
 * @author Asus
 */
public class AccPaymentDash extends javax.swing.JInternalFrame {

    /**
     * Creates new form AccPaymentDash
     */
    public AccPaymentDash() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stdPayBtn = new javax.swing.JButton();
        payDelBtn = new javax.swing.JButton();
        payViewBtn = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stdPayBtn.setBackground(new java.awt.Color(255, 255, 255));
        stdPayBtn.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        stdPayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/cash_in_hand_64px.png"))); // NOI18N
        stdPayBtn.setText("  Student's Payment");
        stdPayBtn.setBorder(null);
        stdPayBtn.setFocusPainted(false);
        stdPayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdPayBtnActionPerformed(evt);
            }
        });

        payDelBtn.setBackground(new java.awt.Color(255, 255, 255));
        payDelBtn.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        payDelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/no_entry_64px.png"))); // NOI18N
        payDelBtn.setText("  Payment Delete    ");
        payDelBtn.setBorder(null);
        payDelBtn.setFocusPainted(false);
        payDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payDelBtnActionPerformed(evt);
            }
        });

        payViewBtn.setBackground(new java.awt.Color(255, 255, 255));
        payViewBtn.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        payViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/file_preview_64px.png"))); // NOI18N
        payViewBtn.setText("  Payment View");
        payViewBtn.setBorder(null);
        payViewBtn.setFocusPainted(false);
        payViewBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        payViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payViewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stdPayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(payViewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(payDelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addGap(260, 260, 260))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(stdPayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(payViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(payDelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stdPayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdPayBtnActionPerformed
        //TODO add your handling code here
        AccountPayment st = new AccountPayment();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_stdPayBtnActionPerformed

    private void payDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payDelBtnActionPerformed
        // TODO add your handling code here:
        AccountPaymentDelete st = new AccountPaymentDelete();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_payDelBtnActionPerformed

    private void payViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payViewBtnActionPerformed
        // TODO add your handling code here:
        AccountPaymentHistoryView st = new AccountPaymentHistoryView();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_payViewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton payDelBtn;
    private javax.swing.JButton payViewBtn;
    private javax.swing.JButton stdPayBtn;
    // End of variables declaration//GEN-END:variables
}
