/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omms.accountantDashboardInternalJframe;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Asus
 */
public class AccPaymentDash extends javax.swing.JInternalFrame {

    /**
     * Creates new form AccPaymentDash
     */
    public AccPaymentDash() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        genBillBtn = new javax.swing.JButton();
        genBillBtn1 = new javax.swing.JButton();
        genBillBtn2 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genBillBtn.setBackground(new java.awt.Color(255, 255, 255));
        genBillBtn.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        genBillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/cash_in_hand_64px.png"))); // NOI18N
        genBillBtn.setText("  Student's Payment");
        genBillBtn.setBorder(null);
        genBillBtn.setFocusPainted(false);
        genBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genBillBtnActionPerformed(evt);
            }
        });

        genBillBtn1.setBackground(new java.awt.Color(255, 255, 255));
        genBillBtn1.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        genBillBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/no_entry_64px.png"))); // NOI18N
        genBillBtn1.setText("  Payment Delete    ");
        genBillBtn1.setBorder(null);
        genBillBtn1.setFocusPainted(false);
        genBillBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genBillBtn1ActionPerformed(evt);
            }
        });

        genBillBtn2.setBackground(new java.awt.Color(255, 255, 255));
        genBillBtn2.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        genBillBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/file_preview_64px.png"))); // NOI18N
        genBillBtn2.setText("  Payment View");
        genBillBtn2.setBorder(null);
        genBillBtn2.setFocusPainted(false);
        genBillBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        genBillBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genBillBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(genBillBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genBillBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genBillBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(260, 260, 260))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(genBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(genBillBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(genBillBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genBillBtnActionPerformed
        // TODO add your handling code here:
        //        ShowLedger st = new ShowLedger();
        //        st.setVisible(true);
        //        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_genBillBtnActionPerformed

    private void genBillBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genBillBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genBillBtn1ActionPerformed

    private void genBillBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genBillBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genBillBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton genBillBtn;
    private javax.swing.JButton genBillBtn1;
    private javax.swing.JButton genBillBtn2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
