/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omms.accountantDashboardInternalJframe;

import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import omms.SecDepUpd;
import omms.SecDepViewCur;
import omms.SecDepViewPrev;

/**
 *
 * @author user
 */
public class AccSecurity extends javax.swing.JInternalFrame {

    /**
     * Creates new form AccSecurity
     */
    public AccSecurity() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        curStdVw = new javax.swing.JButton();
        pervStdVw = new javax.swing.JButton();
        secDepUp = new javax.swing.JButton();

        setOpaque(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        curStdVw.setBackground(new java.awt.Color(255, 255, 255));
        curStdVw.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        curStdVw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/cash_in_hand_64px.png"))); // NOI18N
        curStdVw.setText("Current Students");
        curStdVw.setBorder(null);
        curStdVw.setFocusPainted(false);
        curStdVw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curStdVwActionPerformed(evt);
            }
        });

        pervStdVw.setBackground(new java.awt.Color(255, 255, 255));
        pervStdVw.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        pervStdVw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/cash_in_hand_64px.png"))); // NOI18N
        pervStdVw.setText("Previous Students");
        pervStdVw.setBorder(null);
        pervStdVw.setFocusPainted(false);
        pervStdVw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pervStdVwActionPerformed(evt);
            }
        });

        secDepUp.setBackground(new java.awt.Color(255, 255, 255));
        secDepUp.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        secDepUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/cash_in_hand_64px.png"))); // NOI18N
        secDepUp.setText("Update");
        secDepUp.setBorder(null);
        secDepUp.setFocusPainted(false);
        secDepUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secDepUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pervStdVw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(curStdVw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secDepUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(curStdVw, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(pervStdVw, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(secDepUp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void curStdVwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curStdVwActionPerformed
        //TODO add your handling code here
        SecDepViewCur st = new SecDepViewCur();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_curStdVwActionPerformed

    private void pervStdVwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pervStdVwActionPerformed
        // TODO add your handling code here:
        SecDepViewPrev st = new SecDepViewPrev();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_pervStdVwActionPerformed

    private void secDepUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secDepUpActionPerformed
        // TODO add your handling code here:
        SecDepUpd st = new SecDepUpd();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_secDepUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton curStdVw;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pervStdVw;
    private javax.swing.JButton secDepUp;
    // End of variables declaration//GEN-END:variables
}
