/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omms.accountantDashboardInternalJframe;

import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import omms.NonStoredItemUpdate;
import omms.ShowLedger;
import omms.TempFoodView;

/**
 *
 * @author Asus
 */
public class AccViewDash extends javax.swing.JInternalFrame {

    /**
     * Creates new form AccViewDash
     */
    public AccViewDash() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        showLedgerBtn = new javax.swing.JButton();
        nonStrUpdtBtn = new javax.swing.JButton();
        tempFoodViewBtn = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showLedgerBtn.setBackground(new java.awt.Color(255, 255, 255));
        showLedgerBtn.setFont(new java.awt.Font("Bell MT", 1, 28)); // NOI18N
        showLedgerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/todo_list_64px.png"))); // NOI18N
        showLedgerBtn.setText("  Show Ledger");
        showLedgerBtn.setBorder(null);
        showLedgerBtn.setFocusPainted(false);
        showLedgerBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        showLedgerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLedgerBtnActionPerformed(evt);
            }
        });

        nonStrUpdtBtn.setBackground(new java.awt.Color(255, 255, 255));
        nonStrUpdtBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        nonStrUpdtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/view_64px.png"))); // NOI18N
        nonStrUpdtBtn.setText("  Non Store Item View");
        nonStrUpdtBtn.setBorder(null);
        nonStrUpdtBtn.setFocusPainted(false);
        nonStrUpdtBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        nonStrUpdtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonStrUpdtBtnActionPerformed(evt);
            }
        });

        tempFoodViewBtn.setBackground(new java.awt.Color(255, 255, 255));
        tempFoodViewBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        tempFoodViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/mug.png"))); // NOI18N
        tempFoodViewBtn.setText(" Temporary Food View");
        tempFoodViewBtn.setBorder(null);
        tempFoodViewBtn.setFocusPainted(false);
        tempFoodViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempFoodViewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nonStrUpdtBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tempFoodViewBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showLedgerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(246, 246, 246))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(showLedgerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(nonStrUpdtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(tempFoodViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showLedgerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLedgerBtnActionPerformed
        // TODO add your handling code here:
        ShowLedger st = new ShowLedger();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_showLedgerBtnActionPerformed

    private void nonStrUpdtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonStrUpdtBtnActionPerformed
        // TODO add your handling code here:
        NonStoredItemUpdate st = new NonStoredItemUpdate();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_nonStrUpdtBtnActionPerformed

    private void tempFoodViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempFoodViewBtnActionPerformed
        // TODO add your handling code here:
        TempFoodView st = new TempFoodView();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_tempFoodViewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nonStrUpdtBtn;
    private javax.swing.JButton showLedgerBtn;
    private javax.swing.JButton tempFoodViewBtn;
    // End of variables declaration//GEN-END:variables
}
