/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omms.messDashboardInternalJframe;

import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import omms.CreateDept;
import omms.StdHallAdmission;
import omms.StdInfoDelete;
import omms.StdInfoUpdate;
import omms.StdInfoViewCur;

/**
 *
 * @author Asus
 */
public class MessHallAdmissionDash extends javax.swing.JInternalFrame {

    /**
     * Creates new form HallAdmissionDash
     */
    public MessHallAdmissionDash() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stdAddBtn = new javax.swing.JButton();
        stdView = new javax.swing.JButton();
        stdUpdtBtn = new javax.swing.JButton();
        stdSeatCanBtn = new javax.swing.JButton();
        createDeptBtn = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        stdAddBtn.setBackground(new java.awt.Color(255, 255, 255));
        stdAddBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        stdAddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/admission_64px.png"))); // NOI18N
        stdAddBtn.setText("  Student Admission      ");
        stdAddBtn.setBorder(null);
        stdAddBtn.setFocusPainted(false);
        stdAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdAddBtnActionPerformed(evt);
            }
        });

        stdView.setBackground(new java.awt.Color(255, 255, 255));
        stdView.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        stdView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/view_64px.png"))); // NOI18N
        stdView.setText("  Student's Info View");
        stdView.setBorder(null);
        stdView.setFocusPainted(false);
        stdView.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        stdView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdViewActionPerformed(evt);
            }
        });

        stdUpdtBtn.setBackground(new java.awt.Color(255, 255, 255));
        stdUpdtBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        stdUpdtBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/Stdupdate_64px.png"))); // NOI18N
        stdUpdtBtn.setText("  Student Info Update  ");
        stdUpdtBtn.setBorder(null);
        stdUpdtBtn.setFocusPainted(false);
        stdUpdtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdUpdtBtnActionPerformed(evt);
            }
        });

        stdSeatCanBtn.setBackground(new java.awt.Color(255, 255, 255));
        stdSeatCanBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        stdSeatCanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/delete_database_64px.png"))); // NOI18N
        stdSeatCanBtn.setText("  Student's Seat Cancel");
        stdSeatCanBtn.setBorder(null);
        stdSeatCanBtn.setFocusPainted(false);
        stdSeatCanBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        stdSeatCanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdSeatCanBtnActionPerformed(evt);
            }
        });

        createDeptBtn.setBackground(new java.awt.Color(255, 255, 255));
        createDeptBtn.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        createDeptBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/boxes.png"))); // NOI18N
        createDeptBtn.setText("  Create Department  ");
        createDeptBtn.setBorder(null);
        createDeptBtn.setFocusPainted(false);
        createDeptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDeptBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stdView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdUpdtBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdSeatCanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(createDeptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createDeptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(stdUpdtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(stdView, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(stdSeatCanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 860, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stdUpdtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdUpdtBtnActionPerformed
        // TODO add your handling code here:
        StdInfoUpdate st = new StdInfoUpdate();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_stdUpdtBtnActionPerformed

    private void stdAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdAddBtnActionPerformed
        // TODO add your handling code here:
        StdHallAdmission st = new StdHallAdmission();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_stdAddBtnActionPerformed

    private void stdViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdViewActionPerformed
        // TODO add your handling code here:
        StdInfoViewCur st = new StdInfoViewCur();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_stdViewActionPerformed

    private void stdSeatCanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdSeatCanBtnActionPerformed
        // TODO add your handling code here:
        StdInfoDelete st = new StdInfoDelete();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_stdSeatCanBtnActionPerformed

    private void createDeptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDeptBtnActionPerformed
        // TODO add your handling code here:
        CreateDept st = new CreateDept();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_createDeptBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createDeptBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stdAddBtn;
    private javax.swing.JButton stdSeatCanBtn;
    private javax.swing.JButton stdUpdtBtn;
    private javax.swing.JButton stdView;
    // End of variables declaration//GEN-END:variables
}
