/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omms.hallAuthoDashboardInternalJframe;

import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import omms.AccountPayment;
import omms.AccountPaymentHistoryView;
import omms.BillPermission;
import omms.MessBillView;
import omms.PresentDue;
import omms.SetMealRange;
import omms.StdIndBillStat;

/**
 *
 * @author Asus
 */
public class HallAuthoBillDash extends javax.swing.JInternalFrame {

    /**
     * Creates new form HallAuthoBillDash
     */
    public HallAuthoBillDash() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewMonBillBtn = new javax.swing.JButton();
        payViewBtn = new javax.swing.JButton();
        billGenPerBtn = new javax.swing.JButton();
        billDateRanBtn = new javax.swing.JButton();
        viewDailyBill = new javax.swing.JButton();
        presDueBill = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewMonBillBtn.setBackground(new java.awt.Color(255, 255, 255));
        viewMonBillBtn.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        viewMonBillBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/view_64px.png"))); // NOI18N
        viewMonBillBtn.setText("  Student's Monthly Bill ");
        viewMonBillBtn.setBorder(null);
        viewMonBillBtn.setFocusPainted(false);
        viewMonBillBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        viewMonBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMonBillBtnActionPerformed(evt);
            }
        });

        payViewBtn.setBackground(new java.awt.Color(255, 255, 255));
        payViewBtn.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        payViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/file_preview_64px.png"))); // NOI18N
        payViewBtn.setText("  Payment View                  ");
        payViewBtn.setBorder(null);
        payViewBtn.setFocusPainted(false);
        payViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payViewBtnActionPerformed(evt);
            }
        });

        billGenPerBtn.setBackground(new java.awt.Color(255, 255, 255));
        billGenPerBtn.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        billGenPerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/receipt_64px.png"))); // NOI18N
        billGenPerBtn.setText("Bill Generate Permission");
        billGenPerBtn.setBorder(null);
        billGenPerBtn.setFocusPainted(false);
        billGenPerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billGenPerBtnActionPerformed(evt);
            }
        });

        billDateRanBtn.setBackground(new java.awt.Color(255, 255, 255));
        billDateRanBtn.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        billDateRanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/pay_date_64px.png"))); // NOI18N
        billDateRanBtn.setText("  Bill Date Range Set");
        billDateRanBtn.setBorder(null);
        billDateRanBtn.setFocusPainted(false);
        billDateRanBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        billDateRanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billDateRanBtnActionPerformed(evt);
            }
        });

        viewDailyBill.setBackground(new java.awt.Color(255, 255, 255));
        viewDailyBill.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        viewDailyBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/bill_acc.png"))); // NOI18N
        viewDailyBill.setText("  Student's Daily Bill ");
        viewDailyBill.setBorder(null);
        viewDailyBill.setFocusPainted(false);
        viewDailyBill.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        viewDailyBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDailyBillActionPerformed(evt);
            }
        });

        presDueBill.setBackground(new java.awt.Color(255, 255, 255));
        presDueBill.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        presDueBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/invoice.png"))); // NOI18N
        presDueBill.setText("  Student's Current Due");
        presDueBill.setBorder(null);
        presDueBill.setFocusPainted(false);
        presDueBill.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        presDueBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presDueBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billGenPerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billDateRanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewMonBillBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewDailyBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(presDueBill, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billGenPerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewMonBillBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billDateRanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDailyBill, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(payViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(presDueBill, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewMonBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMonBillBtnActionPerformed
        // TODO add your handling code here:
        MessBillView st = new MessBillView();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_viewMonBillBtnActionPerformed

    private void payViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payViewBtnActionPerformed
        // TODO add your handling code here:
        AccountPaymentHistoryView st = new AccountPaymentHistoryView();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_payViewBtnActionPerformed

    private void billGenPerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billGenPerBtnActionPerformed
        // TODO add your handling code here:
        BillPermission st = new BillPermission();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_billGenPerBtnActionPerformed

    private void billDateRanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billDateRanBtnActionPerformed
        // TODO add your handling code here:
        SetMealRange st = new SetMealRange();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_billDateRanBtnActionPerformed

    private void viewDailyBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDailyBillActionPerformed
        // TODO add your handling code here:
        StdIndBillStat st = new StdIndBillStat();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_viewDailyBillActionPerformed

    private void presDueBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presDueBillActionPerformed
        // TODO add your handling code here:
        PresentDue st = new PresentDue();
        st.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_presDueBillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billDateRanBtn;
    private javax.swing.JButton billGenPerBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton payViewBtn;
    private javax.swing.JButton presDueBill;
    private javax.swing.JButton viewDailyBill;
    private javax.swing.JButton viewMonBillBtn;
    // End of variables declaration//GEN-END:variables
}
